name: Tests

on:
  # Run manually on demand.
  workflow_dispatch:
  # Run automatically when a pull request is created and on each push to it.
  # The runtime is only ~ 30s due to parallelization.
  pull_request:

jobs:
  test:
    name: 'Run unit tests'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ '7.4', '8.2' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install dependencies (using the workflow cache)
        uses: ramsey/composer-install@v2

      - name: Run tests
        run: |
          ./vendor/bin/phpunit --group unit
